version: '3.9'

services:
  app:
    build: .
    restart: always
    ports:
      - '4000:4000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SUPER_ADMIN_USERNAME=${SUPER_ADMIN_USERNAME}
      - SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}
      - SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL}
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: don0
      POSTGRES_DB: movies_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
